version: '3.8'

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fullcycle
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 20s

  node_app:
    build: ./app
    restart: always
    depends_on:
      mysql:
        condition: service_healthy  # Só inicia quando o MySQL estiver pronto
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app_network
    command: ["sh", "-c", "npm install && node index.js"]

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - node_app
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
