version: '3.8'

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fullcycle
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

  node_app:
    build: ./app
    restart: always
    depends_on:
      - mysql
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app_network
    command: ["sh", "-c", "npm install && node index.js"]

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - node_app
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app_network

volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge
